/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { CyberpunkApeLegendsContract } from "./CyberpunkApeLegends";
import { ERC165Contract } from "./ERC165";
import { ERC20Contract } from "./ERC20";
import { ERC721AContract } from "./ERC721A";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC721Contract } from "./IERC721";
import { IERC721EnumerableContract } from "./IERC721Enumerable";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { MigrationsContract } from "./Migrations";
import { MockERC20Contract } from "./MockERC20";
import { OwnableContract } from "./Ownable";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "CyberpunkApeLegends"): CyberpunkApeLegendsContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC721A"): ERC721AContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Enumerable"): IERC721EnumerableContract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "MockERC20"): MockERC20Contract;
      require(name: "Ownable"): OwnableContract;
    }
  }
}

export {
  CyberpunkApeLegendsContract,
  CyberpunkApeLegendsInstance,
} from "./CyberpunkApeLegends";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC721AContract, ERC721AInstance } from "./ERC721A";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721EnumerableContract,
  IERC721EnumerableInstance,
} from "./IERC721Enumerable";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { MockERC20Contract, MockERC20Instance } from "./MockERC20";
export { OwnableContract, OwnableInstance } from "./Ownable";
