/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IMDStakingContract
  extends Truffle.Contract<IMDStakingInstance> {
  "new"(
    _token: string,
    _minYield: number | BN | string,
    _maxYield: number | BN | string,
    _step: number | BN | string,
    _yieldPeriod: number | BN | string,
    meta?: Truffle.TransactionDetails
  ): Promise<IMDStakingInstance>;
}

export interface OwnershipTransferred {
  name: "OwnershipTransferred";
  args: {
    previousOwner: string;
    newOwner: string;
    0: string;
    1: string;
  };
}

export interface Staked {
  name: "Staked";
  args: {
    user: string;
    amount: BN;
    total: BN;
    data: string;
    0: string;
    1: BN;
    2: BN;
    3: string;
  };
}

export interface Unstaked {
  name: "Unstaked";
  args: {
    user: string;
    amount: BN;
    total: BN;
    data: string;
    0: string;
    1: BN;
    2: BN;
    3: string;
  };
}

type AllEvents = OwnershipTransferred | Staked | Unstaked;

export interface IMDStakingInstance extends Truffle.ContractInstance {
  /**
   * Returns the address of the current owner.
   */
  owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
   */
  renounceOwnership: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * The reward token (college credit) to be issued to stakers.
   */
  rewardToken(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * A mapping of token addresses to staking configurations.
   */
  stakableTokenAttributes(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN; 2: BN; 3: BN }>;

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  transferOwnership: {
    (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * owner only.
   * Mints the reward token to an account.
   * @param _amount the amount of tokens to mint.
   * @param _recipient the recipient of the minted tokens.
   */
  mintRewardToken: {
    (
      _recipient: string,
      _amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _recipient: string,
      _amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _recipient: string,
      _amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _recipient: string,
      _amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * owner only, doesn't allow adding already staked tokens.
   * Adds a new token that can be staked in the contract.
   * @param _maxYield the maximum yield for the stakable token.
   * @param _minYield the minimum yield for the stakable token.
   * @param _step the amount yield increases per yield period.
   * @param _token the first stakable token address.
   * @param _yieldPeriod the length (in seconds) of a yield period (the amount of period after which a yield is calculated).
   */
  addStakableToken: {
    (
      _token: string,
      _minYield: number | BN | string,
      _maxYield: number | BN | string,
      _step: number | BN | string,
      _yieldPeriod: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _token: string,
      _minYield: number | BN | string,
      _maxYield: number | BN | string,
      _step: number | BN | string,
      _yieldPeriod: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _token: string,
      _minYield: number | BN | string,
      _maxYield: number | BN | string,
      _step: number | BN | string,
      _yieldPeriod: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _token: string,
      _minYield: number | BN | string,
      _maxYield: number | BN | string,
      _step: number | BN | string,
      _yieldPeriod: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * the contract must be approved to transfer that token first.      the address must be a stakable token.
   * Stakes a given token id from a given contract.
   * @param _token the address of the stakable token.
   * @param _tokenId the id of the token to stake.
   */
  stake: {
    (
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * the contract must be approved to transfer that token first.      the address must be a stakable token.
   * Stakes a given token id from a given contract.
   * @param _token the address of the stakable token.
   * @param _tokenId the id of the token to stake.
   * @param _user the user from which to transfer the token.
   */
  stakeFor: {
    (
      _user: string,
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _user: string,
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _user: string,
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _user: string,
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * reverts if the token is not owned by the caller.
   * Unstakes a given token held by the calling user.
   * @param _token the address of the token contract that the token belongs to.
   * @param _tokenId the id of the token to unstake.
   */
  unstake: {
    (
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Claims the rewards for the caller.
   * @param _token the token for which we are claiming rewards.
   */
  claimRewards: {
    (_token: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(_token: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      _token: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _token: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Gets the College Credit dividend of the provided user.
   * @param _token the token in which we are checking.
   * @param _user the user whose dividend we are checking.
   */
  dividendOf(
    _user: string,
    _token: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  /**
   * reverts if the token is not owned by the caller.
   * Unstakes a given token held by the calling user AND withdraws all dividends.
   * @param _token the address of the token contract that the token belongs to.
   * @param _tokenId the id of the token to unstake.
   */
  unstakeAndClaimRewards: {
    (
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _token: string,
      _tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * reverts if called on an invalid token address.
   * Gets the total amount of tokens staked for the given user in the given contract.
   * @param _token the address of the contract whose staked tokens we are skimming.
   * @param _user the user whose stakes are being counted.
   */
  totalStakedFor(
    _user: string,
    _token: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  /**
   * Gets the total amount staked for a given token address.
   * @param _token the address to get the amount staked from.
   */
  totalStaked(
    _token: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  /**
   * reverts if called on an invalid token address.
   * Gets all of the token ids that a user has staked from a given contract.
   * @param _token the address of the token contract being analyzed.
   * @param _user the user whose token ids are being analyzed.
   */
  stakedTokenIds(
    _user: string,
    _token: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN[]>;

  methods: {
    /**
     * Returns the address of the current owner.
     */
    owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * The reward token (college credit) to be issued to stakers.
     */
    rewardToken(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * A mapping of token addresses to staking configurations.
     */
    stakableTokenAttributes(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN; 2: BN; 3: BN }>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership: {
      (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * owner only.
     * Mints the reward token to an account.
     * @param _amount the amount of tokens to mint.
     * @param _recipient the recipient of the minted tokens.
     */
    mintRewardToken: {
      (
        _recipient: string,
        _amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _recipient: string,
        _amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _recipient: string,
        _amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _recipient: string,
        _amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * owner only, doesn't allow adding already staked tokens.
     * Adds a new token that can be staked in the contract.
     * @param _maxYield the maximum yield for the stakable token.
     * @param _minYield the minimum yield for the stakable token.
     * @param _step the amount yield increases per yield period.
     * @param _token the first stakable token address.
     * @param _yieldPeriod the length (in seconds) of a yield period (the amount of period after which a yield is calculated).
     */
    addStakableToken: {
      (
        _token: string,
        _minYield: number | BN | string,
        _maxYield: number | BN | string,
        _step: number | BN | string,
        _yieldPeriod: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _token: string,
        _minYield: number | BN | string,
        _maxYield: number | BN | string,
        _step: number | BN | string,
        _yieldPeriod: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _token: string,
        _minYield: number | BN | string,
        _maxYield: number | BN | string,
        _step: number | BN | string,
        _yieldPeriod: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _token: string,
        _minYield: number | BN | string,
        _maxYield: number | BN | string,
        _step: number | BN | string,
        _yieldPeriod: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * the contract must be approved to transfer that token first.      the address must be a stakable token.
     * Stakes a given token id from a given contract.
     * @param _token the address of the stakable token.
     * @param _tokenId the id of the token to stake.
     */
    stake: {
      (
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * the contract must be approved to transfer that token first.      the address must be a stakable token.
     * Stakes a given token id from a given contract.
     * @param _token the address of the stakable token.
     * @param _tokenId the id of the token to stake.
     * @param _user the user from which to transfer the token.
     */
    stakeFor: {
      (
        _user: string,
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _user: string,
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _user: string,
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _user: string,
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * reverts if the token is not owned by the caller.
     * Unstakes a given token held by the calling user.
     * @param _token the address of the token contract that the token belongs to.
     * @param _tokenId the id of the token to unstake.
     */
    unstake: {
      (
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Claims the rewards for the caller.
     * @param _token the token for which we are claiming rewards.
     */
    claimRewards: {
      (_token: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _token: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _token: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _token: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Gets the College Credit dividend of the provided user.
     * @param _token the token in which we are checking.
     * @param _user the user whose dividend we are checking.
     */
    dividendOf(
      _user: string,
      _token: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    /**
     * reverts if the token is not owned by the caller.
     * Unstakes a given token held by the calling user AND withdraws all dividends.
     * @param _token the address of the token contract that the token belongs to.
     * @param _tokenId the id of the token to unstake.
     */
    unstakeAndClaimRewards: {
      (
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _token: string,
        _tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * reverts if called on an invalid token address.
     * Gets the total amount of tokens staked for the given user in the given contract.
     * @param _token the address of the contract whose staked tokens we are skimming.
     * @param _user the user whose stakes are being counted.
     */
    totalStakedFor(
      _user: string,
      _token: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    /**
     * Gets the total amount staked for a given token address.
     * @param _token the address to get the amount staked from.
     */
    totalStaked(
      _token: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    /**
     * reverts if called on an invalid token address.
     * Gets all of the token ids that a user has staked from a given contract.
     * @param _token the address of the token contract being analyzed.
     * @param _user the user whose token ids are being analyzed.
     */
    stakedTokenIds(
      _user: string,
      _token: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN[]>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
