/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { CollegeCreditContract } from "./CollegeCredit";
import { ERC20Contract } from "./ERC20";
import { ICollegeCreditContract } from "./ICollegeCredit";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC721Contract } from "./IERC721";
import { IMDStakingContract } from "./IMDStaking";
import { IStakingInterfaceContract } from "./IStakingInterface";
import { MigrationsContract } from "./Migrations";
import { OwnableContract } from "./Ownable";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "CollegeCredit"): CollegeCreditContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ICollegeCredit"): ICollegeCreditContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IMDStaking"): IMDStakingContract;
      require(name: "IStakingInterface"): IStakingInterfaceContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
    }
  }
}

export { CollegeCreditContract, CollegeCreditInstance } from "./CollegeCredit";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export {
  ICollegeCreditContract,
  ICollegeCreditInstance,
} from "./ICollegeCredit";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export { IMDStakingContract, IMDStakingInstance } from "./IMDStaking";
export {
  IStakingInterfaceContract,
  IStakingInterfaceInstance,
} from "./IStakingInterface";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { OwnableContract, OwnableInstance } from "./Ownable";
